(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/template/barrage"],{"35d0":function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var n={props:{barrageList:{type:Array,default:[]},barrageType:{type:Boolean,default:!1}},data:function(){return{barrageInfo:{},topH:null,topW:null,itempx:null,halfcardtext:""}},mounted:function(){var e=this;console.info("barrageInfo",!!e.barrageInfo.avatar),t.getStorage({key:"TextSubstitution",success:function(t){e.halfcardtext=t.data.halfcardtext}}),setTimeout(e.clock(),5e3)},watch:{},onReady:function(){},onHide:function(){console.info("onHide")},onUnload:function(){console.info("onUnload")},methods:{clearSet:function(){console.info("我执行了");var t=this;clearInterval(t.set1),clearInterval(t.set2),clearInterval(t.set3)},clock:function(e,n){var a=this;function o(){var t=Math.ceil(Math.random()*a.barrageList.length);a.barrageInfo=a.barrageList[t-1],console.info("barrageInfo",!!a.barrageInfo.avatar)}function r(){var e=Math.ceil(Math.random()*t.upx2px(400));t.createSelectorQuery().select(".mbList").boundingClientRect(function(n){a.itempx=t.upx2px(750)+"px",a.topH=e+"px"}).exec()}function c(){var t=Math.ceil(Math.random()*n);a.topW=t-a.itempx,a.topW<0?a.topW="0px":a.topW=t-a.itempx+"px"}console.info("执行2"),a.set1=setInterval(o,4e3),a.set2=setInterval(r,4e3),a.set3=setInterval(c,4e3)}}};e.default=n}).call(this,n("543d")["default"])},"4fe4":function(t,e,n){},"86d0":function(t,e,n){"use strict";var a,o=function(){var t=this,e=t.$createElement;t._self._c},r=[];n.d(e,"b",function(){return o}),n.d(e,"c",function(){return r}),n.d(e,"a",function(){return a})},a2a9:function(t,e,n){"use strict";var a=n("4fe4"),o=n.n(a);o.a},bf13:function(t,e,n){"use strict";n.r(e);var a=n("86d0"),o=n("f1b2");for(var r in o)"default"!==r&&function(t){n.d(e,t,function(){return o[t]})}(r);n("a2a9");var c,u=n("f0c5"),i=Object(u["a"])(o["default"],a["b"],a["c"],!1,null,null,null,!1,a["a"],c);e["default"]=i.exports},f1b2:function(t,e,n){"use strict";n.r(e);var a=n("35d0"),o=n.n(a);for(var r in a)"default"!==r&&function(t){n.d(e,t,function(){return a[t]})}(r);e["default"]=o.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/template/barrage-create-component',
    {
        'components/template/barrage-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("bf13"))
        })
    },
    [['components/template/barrage-create-component']]
]);
