(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/template/bindPhone"],{1776:function(e,n,o){"use strict";(function(e){Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var t=i(o("3099"));function i(e){return e&&e.__esModule?e:{default:e}}var a=function(){return o.e("components/template/PopManager").then(o.bind(null,"b696"))},u={components:{PopManager:a},props:{phoneShow:{type:Boolean,default:function(){return!1}}},data:function(){return{showB:!0,memberInfo:{nickname:""},pinText:"获取验证码",show:!1,phone:"",smsCode:"",getSmsCode:"",textList:{},TextSubstitution:{},scollHeight:null,fullHeight:null,card:"",timeCount:0,timeEnd:"",login:!0}},methods:{ComMobileBlur:function(){var e=this;e.$emit("mobileBulr","mbInputBlur")},closePop:function(){this.$emit("clickmask")},PIN:function(){var n=this;if(n.show=!0,""!=n.phone&&11===n.phone.length){var o={phone:n.phone,type:2};t.default._post_form("&do=PIN",o,function(e){var o=60,t=setInterval(function(){o--,n.timeEnd=o+"s后重试",n.timeCount=o,0==o&&clearInterval(t)},1e3);n.getSmsCode=e.data.code})}else e.showToast({icon:"none",title:"请输入正确的手机号",duration:2e3})},changeMobile:function(){var n=this;if(""!=n.phone&&11===n.phone.length)if(console.log(""===n.smsCode),""!==n.smsCode){var o={mobile:n.phone,mergeflag:"",code:n.smsCode};t.default._post_form("&p=member&do=changeMobile",o,function(o){n.newPhoneShow=!1,n.showB=!1,n.phone="",n.smsCode="",e.showToast({icon:"none",title:"修改成功",duration:2e3})},function(o){o.data.data.code&&1===o.data.data.code||e.showModal({title:"友情提示",content:o.data.message,showCancel:!0,success:function(o){if(o.confirm){var i={mobile:n.phone,mergeflag:1,code:n.smsCode};t.default._post_form("&p=member&do=changeMobile",i,function(o){n.newPhoneShow=!1,n.phone="",n.showB=!1,n.smsCode="",e.showToast({icon:"none",title:"修改成功",duration:2e3})})}}})})}else e.showToast({icon:"none",title:"验证码不能为空",duration:2e3});else e.showToast({icon:"none",title:"请输入正确的手机号",duration:2e3})}},computed:{newPhoneShow:{get:function(){return this.phoneShow},set:function(e){return this.val}}}};n.default=u}).call(this,o("543d")["default"])},4616:function(e,n,o){"use strict";var t,i=function(){var e=this,n=e.$createElement;e._self._c},a=[];o.d(n,"b",function(){return i}),o.d(n,"c",function(){return a}),o.d(n,"a",function(){return t})},"58dc":function(e,n,o){"use strict";o.r(n);var t=o("4616"),i=o("7535");for(var a in i)"default"!==a&&function(e){o.d(n,e,function(){return i[e]})}(a);o("f64b");var u,s=o("f0c5"),c=Object(s["a"])(i["default"],t["b"],t["c"],!1,null,null,null,!1,t["a"],u);n["default"]=c.exports},7535:function(e,n,o){"use strict";o.r(n);var t=o("1776"),i=o.n(t);for(var a in t)"default"!==a&&function(e){o.d(n,e,function(){return t[e]})}(a);n["default"]=i.a},"9b8d":function(e,n,o){},f64b:function(e,n,o){"use strict";var t=o("9b8d"),i=o.n(t);i.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/template/bindPhone-create-component',
    {
        'components/template/bindPhone-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("58dc"))
        })
    },
    [['components/template/bindPhone-create-component']]
]);
