(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/template/follow"],{1266:function(t,o,n){"use strict";var e=n("3dcc"),l=n.n(e);l.a},"1b08":function(t,o,n){"use strict";(function(t){Object.defineProperty(o,"__esModule",{value:!0}),o.default=void 0;var e=l(n("3099"));function l(t){return t&&t.__esModule?t:{default:t}}var a=function(){return n.e("components/template/PopManager").then(n.bind(null,"b696"))},u={components:{PopManager:a},props:{shareId:{type:String,default:""},followShow:{type:Boolean,default:!1},followType:{type:String,default:""},followTitleShow:{type:Boolean,default:!1}},data:function(){return{type:null,platformInfor:{},followInfo:{status:0}}},mounted:function(){var o=this;"0"==o.followType?o.type="center":o.type="bottom",o.platformInfor=t.getStorageSync("platformInfor"),o.init()},methods:{closePop:function(){var t=this;t.$emit("closeFollowPop")},closeFollowTitle:function(){var t=this;t.$emit("closeFollowTitle")},init:function(){var t=this;t.getFollow()},getFollow:function(){var t=this,o={type:t.followType,id:t.shareId||""};e.default._post_form("&do=Follow",o,function(o){console.info(o.data),t.followInfo=o.data})},openQrShow:function(){var t=this;t.$emit("clickmask")}}};o.default=u}).call(this,n("543d")["default"])},"273b":function(t,o,n){"use strict";n.r(o);var e=n("1b08"),l=n.n(e);for(var a in e)"default"!==a&&function(t){n.d(o,t,function(){return e[t]})}(a);o["default"]=l.a},"3dcc":function(t,o,n){},"70b1":function(t,o,n){"use strict";var e,l=function(){var t=this,o=t.$createElement;t._self._c},a=[];n.d(o,"b",function(){return l}),n.d(o,"c",function(){return a}),n.d(o,"a",function(){return e})},c771:function(t,o,n){"use strict";n.r(o);var e=n("70b1"),l=n("273b");for(var a in l)"default"!==a&&function(t){n.d(o,t,function(){return l[t]})}(a);n("1266");var u,f=n("f0c5"),r=Object(f["a"])(l["default"],e["b"],e["c"],!1,null,null,null,!1,e["a"],u);o["default"]=r.exports}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/template/follow-create-component',
    {
        'components/template/follow-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("c771"))
        })
    },
    [['components/template/follow-create-component']]
]);
