(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/template/shareBottom"],{"3de3":function(t,e,o){"use strict";o.r(e);var n=o("9ee0"),a=o.n(n);for(var s in n)"default"!==s&&function(t){o.d(e,t,function(){return n[t]})}(s);e["default"]=a.a},"3e1f":function(t,e,o){},"51ae":function(t,e,o){"use strict";var n=o("3e1f"),a=o.n(n);a.a},"6ab4":function(t,e,o){"use strict";var n,a=function(){var t=this,e=t.$createElement;t._self._c;t._isMounted||(t.e0=function(e){t.iscardPost=!1})},s=[];o.d(e,"b",function(){return a}),o.d(e,"c",function(){return s}),o.d(e,"a",function(){return n})},"9ee0":function(t,e,o){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var n=a(o("3099"));function a(t){return t&&t.__esModule?t:{default:t}}var s=function(){return o.e("components/template/PopManager").then(o.bind(null,"b696"))},i={components:{PopManager:s},props:{shareShow:{type:Boolean,default:!1},shareBottomShow:{type:Boolean,default:!1},postType:{type:String,default:""},postId:{type:String,default:""},isCard:{type:Boolean,default:function(){return!1}}},data:function(){return{shareType:"top",type:"bottom",cardPostImage:null,iscardPost:!1}},methods:{closeShareShow:function(){this.$emit("closeShareShow")},shareImgShow:function(){this.$emit("shareImgShow","imageShow")},saveCardImage:function(e){t.downloadFile({url:e,success:function(e){200===e.statusCode&&t.saveImageToPhotosAlbum({filePath:e.tempFilePath,success:function(t){n.default.showSuccess("保存成功")},complete:function(){t.hideLoading()}})}})},goHb:function(){var e=this,o=this.isCard;console.log(o),o?(t.showLoading({}),n.default._post_form("&do=Poster",{type:"11",id:e.postId},function(t){e.setData({cardPostImage:t.data.url,iscardPost:!0})},!1,function(){t.hideLoading()}),e.$emit("gohb","showPost")):n.default.navigationTo({url:"pages/mainPages/poster/poster?id="+e.postId+"&type="+e.postType})},goTg:function(){var t=this;n.default.navigationTo({url:"pages/subPages/shareMaterials/index?id="+t.postId+"&type="+t.postType})},closeShareBottom:function(){this.$emit("clickmask")},closeCardPost:function(){this.iscardPost=!1}}};e.default=i}).call(this,o("543d")["default"])},cb2e:function(t,e,o){"use strict";o.r(e);var n=o("6ab4"),a=o("3de3");for(var s in a)"default"!==s&&function(t){o.d(e,t,function(){return a[t]})}(s);o("51ae");var i,u=o("f0c5"),r=Object(u["a"])(a["default"],n["b"],n["c"],!1,null,null,null,!1,n["a"],i);e["default"]=r.exports}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/template/shareBottom-create-component',
    {
        'components/template/shareBottom-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("cb2e"))
        })
    },
    [['components/template/shareBottom-create-component']]
]);
