(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/template/storeGoods"],{2093:function(t,o,e){"use strict";e.r(o);var n=e("6a3d"),a=e("3e50");for(var r in a)"default"!==r&&function(t){e.d(o,t,function(){return a[t]})}(r);e("8ffe");var u,i=e("f0c5"),c=Object(i["a"])(a["default"],n["b"],n["c"],!1,null,"46bf7748",null,!1,n["a"],u);o["default"]=c.exports},"3e50":function(t,o,e){"use strict";e.r(o);var n=e("5a9e"),a=e.n(n);for(var r in n)"default"!==r&&function(t){e.d(o,t,function(){return n[t]})}(r);o["default"]=a.a},"52cd":function(t,o,e){},"5a9e":function(t,o,e){"use strict";(function(t){Object.defineProperty(o,"__esModule",{value:!0}),o.default=void 0;var n=a(e("3099"));function a(t){return t&&t.__esModule?t:{default:t}}function r(t){return c(t)||i(t)||u()}function u(){throw new TypeError("Invalid attempt to spread non-iterable instance")}function i(t){if(Symbol.iterator in Object(t)||"[object Arguments]"===Object.prototype.toString.call(t))return Array.from(t)}function c(t){if(Array.isArray(t)){for(var o=0,e=new Array(t.length);o<t.length;o++)e[o]=t[o];return e}}var d={data:function(){return{goodsData:[],totalPage:null,slide_Top:0,current_page:1,loading:!1}},props:{storeId:{type:String,default:function(){return""}},tabType:{type:String,default:function(){return""}}},methods:{getStoreGoods:function(){var o=arguments.length>0&&void 0!==arguments[0]?arguments[0]:1,e=arguments.length>1&&void 0!==arguments[1]&&arguments[1],a=this,u={sid:a.storeId,page:o};n.default._post_form("&p=store&do=getStoreGoods",u,function(t){var o,n=t.data;e?n.list.length>0?(o=a["goodsData"]).push.apply(o,r(n.list)):a.loading=!0:a.setData({goodsData:t.data.list,totalPage:t.data.total})},!1,function(){t.hideLoading()})},scrolly:function(t){this.slide_Top=t.detail.scrollTop},ReachBottom:function(){console.info("ReachBottomGoods");var t=this;if(t.current_page>=t.totalPage)return!1;t.getStoreGoods(++t.current_page,!0)},tabbarShow:function(){var o=this;t.showLoading(),o.slide_Top=0,o.current_page=1,o.getStoreGoods()},naviGoods:function(t,o){var e={id:t,type:o};n.default.navigationTo({url:"pages/subPages/goods/index?"+n.default.urlEncode(e)})}},onLoad:function(t){},mounted:function(){},computed:{},components:{},watch:{storeId:function(t,o){this.getStoreGoods()}}};o.default=d}).call(this,e("543d")["default"])},"6a3d":function(t,o,e){"use strict";var n,a=function(){var t=this,o=t.$createElement,e=(t._self._c,t.__map(t.goodsData,function(o,e){var n=Number(o.buy_percentage),a=Number(o.buy_percentage);return{$orig:t.__get_orig(o),m0:n,m1:a}}));t.$mp.data=Object.assign({},{$root:{l0:e}})},r=[];e.d(o,"b",function(){return a}),e.d(o,"c",function(){return r}),e.d(o,"a",function(){return n})},"8ffe":function(t,o,e){"use strict";var n=e("52cd"),a=e.n(n);a.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/template/storeGoods-create-component',
    {
        'components/template/storeGoods-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("2093"))
        })
    },
    [['components/template/storeGoods-create-component']]
]);
