(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/page/pageComponents/Video"],{"538c":function(t,e,n){"use strict";var i=n("b984"),o=n.n(i);o.a},"5b86":function(t,e,n){"use strict";var i,o=function(){var t=this,e=t.$createElement;t._self._c},a=[];n.d(e,"b",function(){return o}),n.d(e,"c",function(){return a}),n.d(e,"a",function(){return i})},a2a30:function(t,e,n){"use strict";n.r(e);var i=n("5b86"),o=n("c433");for(var a in o)"default"!==a&&function(t){n.d(e,t,function(){return o[t]})}(a);n("538c");var c,u=n("f0c5"),d=Object(u["a"])(o["default"],i["b"],i["c"],!1,null,"7a1a3c3c",null,!1,i["a"],c);e["default"]=d.exports},b984:function(t,e,n){},c433:function(t,e,n){"use strict";n.r(e);var i=n("e050"),o=n.n(i);for(var a in i)"default"!==a&&function(t){n.d(e,t,function(){return i[t]})}(a);e["default"]=o.a},e050:function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var n=null,i={data:function(){return{isVideoPlay:!1,videoHeight:240,muted:!1}},props:{itemIndex:Number,itemStyle:Object,params:Object,itemId:String},components:{},computed:{},beforeCreate:function(){},onLoad:function(t){},onShow:function(){},onReady:function(){n=t.createVideoContext(this.itemId,this)},mounted:function(){var e=this,n=e.params,i=e.itemStyle,o={1:16/9,2:4/3,3:1};"2"===n.videotype&&t.getSystemInfo({success:function(t){var n=t.windowWidth,a=o[i.display];console.log("videoHeight",n/a),e.videoHeight=n/a}})},methods:{imageLoad:function(e){var n=this;"1"===n.params.videotype&&n.params.videocover&&t.getSystemInfo({success:function(t){var i=t.windowWidth,o=e.detail,a=o.width/o.height;n.videoHeight=i/a}})},videoPlay:function(t){var e=this;e.isVideoPlay=!0,setTimeout(function(){console.log("video play"),n.play()},200)},showVideoStatus:function(t){t.currentTarget.id;var e,n=t.type;e="play"==n,this.isVideoPlay=e},videoMuted:function(t){console.log("muted"),this.muted=!this.muted}},watch:{isVideoPlay:function(e,i){n=t.createVideoContext(this.itemId,this)}}};e.default=i}).call(this,n("543d")["default"])}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/page/pageComponents/Video-create-component',
    {
        'components/page/pageComponents/Video-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("a2a30"))
        })
    },
    [['components/page/pageComponents/Video-create-component']]
]);
